### ISSUE TITLE
Can't get the tunnel to work

### ISSUE THREAD

**Issue by alexlafroscia** [browserstack/browserstack-testem-integration#1]
I can't seem to get the tunnel working at all.  I've copied the example `testem.json` config exactly.  The `browserstack tunnel ...` command seems to just time out instantly...

```
not ok 1 Error
    ---
        message: >
            Timed out without seeing Tunnel is running
    ...

1..1
# tests 1
# pass  0
# fail  1
```

Any help?

**Comment by alexlafroscia** [comment]
Issue opened on the main Testem repo here: https://github.com/airportyh/testem/issues/604

**Comment by vedharish** [comment]
The issue on testem repo was closed as @alexlafroscia was able to get the tests to work.

The tunnel connection time-out problem was because of the browserstack-cli module not being updated to BrowserStack features. The support for `local jar` was stopped in favor of [BrowserStack Local Binary](https://www.browserstack.com/local-testing). This example no longer uses the module. I believe this is no longer a problem for the updated code example.

@alexlafroscia Can you please close if this is no longer an issue.
